version: "3.9"
services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - PUID=0
            - PGID=0
            - TZ=$tzone
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
            - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource
        volumes:
            - grafana-data:/var/lib/grafana
            - ${app_data}/grafana/grafana.ini:/etc/grafana/grafana.ini
        ports:
            - 3000:3000
        restart: always
        networks:
            - private
volumes:
  grafana-data:
    external: true

networks:
    private:
        external: true
