version: "3.9"
services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - PUID=0
            - PGID=0
            - TZ=$tzone
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
            - GF_PATHS_CONFIG=${app_data}/grafana/grafana.ini
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - 3000:3000
        restart: always
        networks:
            - private
volumes:
  grafana-data:
    external: true

networks:
    private:
        external: true
